flags:
  generic-deriving:
    base-4-9: false
  transformers-compat:
    four: true
packages:
- .
extra-deps:
- Cabal-1.22.5.0
- JuicyPixels-3.2.9.5
- cabal-macosx-0.2.4.1
- directory-1.2.7.1
- fail-4.9.0.0
- fgl-5.6.0.0
- generic-deriving-1.12.1
- hashable-1.2.7.0
- hscolour-1.24.4
- mtl-2.2.2
- parsec-3.1.13.0
- pqueue-1.3.2.3
- primitive-0.6.3.0
- reactive-banana-1.1.0.1
- reactive-banana-wx-1.1.1.0
- semigroups-0.18.4
- split-0.2.3.3
- stm-2.4.5.0
- strict-0.3.2
- tagged-0.8.5
- text-1.2.3.0
- transformers-compat-0.6.2
- unordered-containers-0.2.9.0
- vault-0.3.1.0
- vector-0.12.0.1
- wx-0.92.1.0
- wxc-0.92.1.0
- wxcore-0.92.1.0
- wxdirect-0.92.1.0
- zlib-0.6.2

resolver: ghc-7.10.3

explicit-setup-deps:
  "reactive-banana-wx": true
