# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.0

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - Cabal-1.22.5.0
  - cabal-macosx-0.2.3.4
  - reactive-banana-1.1.0.1
  - reactive-banana-wx-1.1.1.0
  - wx-0.92.2.0
  - wxcore-0.92.2.0
  - wxc-0.92.2.0
  - wxdirect-0.92.2.0

explicit-setup-deps:
  "reactive-banana-wx": true